name: Build & Push Resume PDF

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout resume source
        uses: actions/checkout@v4

      - name: Install Typst
        run: |
          wget -q https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
          tar -xf typst-x86_64-unknown-linux-musl.tar.xz
          sudo install -m 755 typst-x86_64-unknown-linux-musl/typst /usr/local/bin/typst
          rm -rf typst-x86_64-unknown-linux-musl*

      - name: Compile Typst to PDF
        run: |
          mkdir -p out
          typst compile --font-path ./assets/fonts/ ./resume.typ resume-patrick-ambrose.pdf

          - name: Push to portfolio repo
          env:
            TARGET_REPO: patpuccin/portfolio
            TARGET_PATH: public/resume-patrick-ambrose.pdf
          run: |
            set -e  # exit on first error
        
            # Configure Git identity for CI commits
            git config --global user.name "Pat Ambrose (CI)"
            git config --global user.email "actions@github.com"
            git config --global advice.detachedHead false
            git config --global init.defaultBranch main
        
            # Clone the target repo (shallow for performance)
            git clone --depth 1 https://${{ secrets.RESUME_PUSH_TO_PORTFOLIO_REPO }}@github.com/${TARGET_REPO}.git target-repo
        
            # Copy the generated PDF into the correct location
            cp resume-patrick-ambrose.pdf target-repo/${TARGET_PATH}
        
            cd target-repo
        
            # Add and commit changes if any
            git add ${TARGET_PATH}
            git diff --cached --quiet || git commit -m "chore(ci): update resume PDF ($(date +'%Y-%m-%d %H:%M:%S'))"
        
            # Push to main
            git push origin main
        